"""change column type

Revision ID: b147f47cefde
Revises: 
Create Date: 2023-01-22 13:51:20.354094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b147f47cefde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.alter_column('access_exp',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.DateTime(timezone=256),
               existing_nullable=False)
        batch_op.alter_column('refresh_exp',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.DateTime(timezone=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.alter_column('refresh_exp',
               existing_type=sa.DateTime(timezone=256),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.alter_column('access_exp',
               existing_type=sa.DateTime(timezone=256),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###
